sitio/urls.py
from django.contrib import admin
from django.urls import path, include
#URLS SITIO
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sushi.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

sushi/urls.py
from django.urls import path, include
from .views import index, mispedidos, productos, crearproducto, modificarproducto, eliminarproducto,logout_view,\
    registro
    

#IMAGEN
from django.conf import settings
from django.conf.urls.static import static

#URLS APP
urlpatterns = [
    path('', index, name='index'),
    path('mispedidos/', mispedidos, name='mispedidos'),
    path('productos/', productos, name='productos'),
    path('crearproducto/',crearproducto, name='crearproducto'),
    path('modificarproducto/<id>',modificarproducto, name='modificarproducto'),
    path('eliminarproducto/<id>',eliminarproducto,name='eliminarproducto'),
    path('logout_view/',logout_view,name='logout_view'),
    path('registro',registro,name='registro')
    
 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sushi/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    nombre_producto=models.CharField(max_length=50, null=False)
    imagen=models.ImageField(upload_to='productos', null=True)
    descripcion=models.CharField(max_length=50, null=False)
    valor=models.IntegerField(null=False)
    


    def __str__(self):
        return self.nombre_producto

sushi/forms.py
from django import forms
from .models import Producto
from django.contrib.auth.forms import UserCreationForm

class customUserCreationForm(UserCreationForm):
    pass




class ProductoForm(forms.ModelForm):
    nombre_producto=forms.CharField(widget=forms.TextInput(),help_text='Ingrese nombre del producto')
    descripcion=forms.CharField(widget=forms.TextInput())
    valor=forms.IntegerField(min_value=1000, max_value=10000, localize=True)
    imagen=forms.ImageField()
                                    
    class Meta:
        model = Producto
        fields = ['nombre_producto', 'descripcion', 'valor', 'imagen']

sushi/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from .forms import ProductoForm, customUserCreationForm
from .models import	Producto
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib.auth import logout
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User



# Create your views here.
def index(request):
    return render(request, 'sushi/index.html')

def mispedidos(request):
    return render(request, 'sushi/mispedidos.html')

def productos(request):
    
    
    productos=Producto.objects.all()
    page=request.GET.get('page',1)
    
    try:
        pagtr=Paginator(productos,3)
        productos=pagtr.page(page)
    except:
        raise Http404
    
    print(productos)
    datos={
        "productos":productos,
        "paginator":pagtr
    }
    
    if request.method=="POST":
        val=request.POST.get("valor")
        productos=Producto.objects.filter(valor=val)
        
        datos={
        "productos":productos,
      
        }
        
    return render(request,'sushi/productos.html', datos)

def crearproducto(request):
    form=ProductoForm()
    datos={
        'form':form
    }
    
    if request.method=='POST':
        form=ProductoForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            datos["mensaje"]='Producto Agregado'
            messages.success(request,'Producto agregado exitosamente!!')
            return redirect('productos')
        else:
            datos["form"]=form
            
    return render(request,'sushi/crearproducto.html',datos)

def modificarproducto(request,id):
    prod=get_object_or_404(Producto, id=id)
    form=ProductoForm(instance=prod)
    
    datos={
        "form":form
    }
    
    if request.method=="POST":
        form=ProductoForm(data=request.POST, files=request.FILES, instance=prod)
        if form.is_valid():
            form.save()
            messages.set_level(request,messages.SUCCESS)
            messages.success(request,'Producto actualizado exitosamente!!')
            return redirect(to='productos')
    
 
    return render(request,'sushi/modificarproducto.html',datos)

def eliminarproducto(request,id):
    producto=get_object_or_404(Producto,id=id)
    
    datos={
        "producto":producto
    }
    
    if request.method=="POST":
        import os
        os.remove(os.path.join(str(settings.MEDIA_ROOT).replace('/media','')+str(producto.imagen.url).replace('/','\\')))
        producto.delete()
        messages.set_level(request, messages.WARNING)
        messages.warning(request,"El producto fue eliminado correctamente!!")
        return redirect(to='productos')
    
    return render(request,'sushi/eliminarproducto.html', datos)

def logout_view(request):
    logout(request) #from django.contrib.auth import logout
    messages.set_level(request,messages.INFO)
    messages.info(request,"Sesión Terminada!!!")
    return redirect(to='index')

def registro(request):
    datos={
        "form":customUserCreationForm()
    }
    
    if request.method=="POST":
        form=customUserCreationForm(data=request.POST)
        newusr=request.POST.get('username')

        existe=User.objects.filter(username=newusr)
        print(existe)
        if len(existe)==0:
            if form.is_valid():
                
                form.save()
                usuario=authenticate(username=form.cleaned_data["username"],password=form.cleaned_data["password1"])
                login(request, usuario)
                messages.success(request,"Usuario creado exitosamente")
                return redirect(to="index")
        else:
            
            datos={
                "form":customUserCreationForm(),
                "alerta": 'Usuario Existente'
            }
                
                
    return render(request,'registration/registro.html', datos)

sushi/templates/sushi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sushi delivery</title>
    <!-- Latest compiled and minified CSS -->
    <link href="{% static 'sushi/css/bootstrap.min.css' %} " rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src=" {% static 'sushi/js/bootstrap.bundle.min.js' %} "></script>
    <link rel="stylesheet" href=" {% static 'sushi/css/estilo.css' %} ">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        {% if message.level == 25 %}
        <script>
            Swal.fire({
                title: 'Exito!',
                text: '{{message}} {{message.level}}',
                icon: 'success',
                confirmButtonText: 'Ok'
            })


        </script>
        {% endif %}
        {% if message.level == 30 %}
        <script>
            Swal.fire({
                title: 'Exito!',
                text: '{{message}} {{message.level}}',
                icon: 'warning',
                confirmButtonText: 'Ok'
            })


        </script>
        {% endif %}
        {% if message.level == 20 %}
        <script>
            Swal.fire({
                title: 'Hasta Pronto!',
                text: '{{message}}',
                icon: 'info',
                confirmButtonText: 'Ok'
            })


        </script>
        {% endif %}
        {% endfor %}
    </ul>
    {% endif %}

    {% block links %}

    {% endblock links %}



</head>

<body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-danger">
        <div class="container">

            <a class="navbar-brand" href="{% url 'index' %}">
                <img src=" {% static 'sushi/img/dog3logo.png' %} " alt=" Avatar Logo" style="width:40px;"
                class="rounded-pill">
            </a>

            <a class="navbar-brand" href="{% url 'index' %}">Sushiwawa</a>
            <button class=" navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" href=" {% url 'index' %}" aria-current="page">Home
                                <span class="visually-hidden">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Menú</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mispedidos' %}">Mis pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Contacto</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">Administración</a>
                            <div class="dropdown-menu bg-danger shadow drophovercustom" aria-labelledby="dropdownId">
                                <a class="dropdown-item drophovercustom" href=" {% url 'productos' %}">Productos</a>
                                <a class="dropdown-item drophovercustom" href="">Pedidos</a>
                                <a class="dropdown-item drophovercustom" href="">Clientes</a>
                            </div>
                        </li>
                    </ul>
                    <!-- <ul class="navbar-nav me-auto mt-2 mt-lg-0 " >
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuario</a>
                    </li>
                </ul> -->
                 
                    {% if user.is_authenticated %}
                        <span id="sesionlink"><a class="nav-link text-light sesiontext" href="">{{user.username}} |</a></span>
                       {% comment %}  <form action="{% url "logout" %}" method="post">
                            {% csrf_token %}
                            <span id="sesionlink"><button type="submit" class='nav-link text-light sesiontext'>&nbsp;Cerrar Sesión</button></span>
                        </form> {% endcomment %}

                        <span id="sesionlink"><a class="nav-link text-light sesiontext" href="{% url "logout_view" %}">&nbsp;Cerrar Sesión</a></span>
                    {% else %}
                        <span id="sesionlink"><a class="nav-link text-light sesiontext" href="{% url 'login' %}">Iniciar Sesión</a></span>
                        <span id="sesionlink"><a class="nav-link text-light sesiontext" href="">|</a></span>
                        <span id="sesionlink"><a class="nav-link text-light sesiontext" href="{% url 'registro' %}">Crear cuenta</a></span>
                    {% endif %}


                </div>
        </div>
    </nav>
    {% block contenido %}



    {% endblock contenido %}







</body>

</html>

sushi/templates/sushi/crearcuenta.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sushi delivery</title>
    <!-- Latest compiled and minified CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="css/estilocrearcuenta.css">
    <link rel="stylesheet" href="css/estilo.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-danger">
        <div class="container">

            <a class="navbar-brand" href="#">
                <img src="img/dog3logo.png" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
            </a>

            <a class="navbar-brand" href="#">Sushiwawa</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="index.html" aria-current="page">Home
                            <span class="visually-hidden">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="menu.html">Menú</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="mispedidos.html">Mis pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacto.html">Contacto</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Administración</a>
                        <div class="dropdown-menu bg-danger shadow" aria-labelledby="dropdownId">
                            <a class="dropdown-item drophovercustom" href="productos.html">Productos</a>
                            <a class="dropdown-item drophovercustom" href="pedidos.html">Pedidos</a>
                            <a class="dropdown-item drophovercustom" href="clientes.html">Clientes</a>
                        </div>
                    </li>
                </ul>
                <!-- <ul class="navbar-nav me-auto mt-2 mt-lg-0 " >
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuario</a>
                    </li>
                </ul> -->
                <span id="sesionlink"><a class="nav-link text-light sesiontext" href="login.html">Usuario</a></span>

            </div>
        </div>
    </nav>
    <div class="container"><!--main container-->



        <div class="row mt-3">
            <div class="col-sm"></div>
            <div class="col-sm">
                <h2 class="text-center">Crear cuenta</h2>
                <form action="login.html" class="was-validated">
                    <div class="mb-3">
                        <label for="usrname" class="form-label">Nombre de Usuario:</label>
                        <input type="text" class="form-control" id="usrname" name="usrname" placeholder="waco123"
                            required>
                        
                        <div class="invalid-feedback">Complete este campo</div>
                    </div>
                    <div class="mb-3 mt-3">
                        <label for="email" class="form-label">Email:</label>
                        <input type="email" class="form-control" id="email" placeholder="Ingrese email" name="email"
                            required>
                            <div class="invalid-feedback">Complete este campo</div>
                    </div>
                    <div class="mb-3">
                        <label for="pwd" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd"
                            required>
                            <div class="invalid-feedback">Complete este campo</div>
                    </div>
                    <div class="mb-3">
                        <label for="pwd2" class="form-label">Reingrese Password:</label>
                        <input type="password" class="form-control" id="pwd2" placeholder="reingrese password"
                            name="pswd2" required>
                            <div class="invalid-feedback">Complete este campo</div>
                    </div>
                    <div class="mb-3">
                        <label for="dire" class="form-label">Dirección:</label>
                        <input type="text" class="form-control" id="dire" placeholder="Ej.: por ahi 123" name="dire"
                            required>
                            <div class="invalid-feedback">Complete este campo</div>
                    </div>
                    <div class="form-check mb-3">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox" name="remember"> Desea recibir
                            notificaciones
                        </label>
                    </div>
                    <button type="submit" class="btncrear rounded">Crear cuenta</button><br>
                    <br>
                    <button type="reset" class="btncancelar rounded">Cancelar</button>
                </form>




            </div>
            <div class="col-sm"></div>

        </div>






    </div><!--main container ends-->



</body>

</html>

sushi/templates/sushi/crearproducto.html
{% extends "sushi/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="container">

    <div class="row mt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="border shadow rounded p-5">
                <h3>Nuevo Producto</h3>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <input type="submit" class="btn btn-success btn-lg mt-2" value="Enviar">
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>


</div>



{% endblock contenido %}

sushi/templates/sushi/eliminarproducto.html
{% extends "sushi/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="container">
    <div class="alert alert-danger mt-4" role="alert">
        <strong>ATENCIÓN: Está a punto de eliminar un producto</strong>
    </div>
    <div class="border shadow rounded p-5">

        <div>
            <h3>¿Estás seguro de eliminar el siguiente producto ?</h3>
            <h1>{{ producto.nombre_producto }}</h1>
        </div>
        <div>


            <div class="d-flex justify-content-end">
                <input type="button" class="btn btn-danger btn-lg mt-2" value="Eliminar" data-bs-toggle="modal"
                    data-bs-target="#myModal">
                <span> &nbsp;&nbsp;</span>
                <a href="{% url 'productos' %}">
                    <input type="button" class="btn btn-success btn-lg mt-2" value="Cancelar">
                </a>


            </div>


            <!-- The Modal -->
            <div class="modal fade" id="myModal">

                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Modal Header -->
                            <div class="modal-header">
                                <h4 class="modal-title">Confirmar eliminación</h4>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>

                            <!-- Modal body -->
                            <div class="modal-body">
                                Confirme que desea eliminar {{ producto.nombre_producto }}
                            </div>

                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Eliminar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



{% endblock contenido %}

sushi/templates/sushi/index.html
{% extends "sushi/base.html" %}
{% load static %}



{% block contenido %}
<div class="container">

    <div class="col-lg">
        <div class="mt-1 p-2 bg-light text-dark rounded text-center">
            <h1 class="display-1">SushiWawa</h1>
            <img src=" {% static 'sushi/img/dog3transp.png' %} " alt="logo" height="180vw">
            <p>The best sushi of the f'world!!!</p>
        </div>
    </div>

    <!--  -->
    <div class="row mt-2">
        <div id="demo" class="carousel slide" data-bs-ride="carousel">

        <!-- Indicators/dots -->
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
        </div>

        <!-- The slideshow/carousel -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'sushi/img/sushiroll1.jpg' %}" alt="sushi1" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'sushi/img/sushiroll2.jpg' %}" alt="sushi2" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'sushi/img/sushiroll3.jpg' %}" alt="sushi3" class="d-block w-100">
            </div>
        </div>

        <!-- Left and right controls/icons -->
        <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>
</div>



</div>
{% endblock contenido %}

sushi/templates/sushi/menu.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sushi delivery</title>
    <!-- Latest compiled and minified CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="css/estilo.css">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-danger">
        <div class="container">

            <a class="navbar-brand" href="#">
                <img src="img/dog3logo.png" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
            </a>

            <a class="navbar-brand" href="#">Sushiwawa</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="index.html" aria-current="page">Home
                            <span class="visually-hidden">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="menu.html">Menú</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="mispedidos.html">Mis pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacto.html">Contacto</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Administración</a>
                        <div class="dropdown-menu bg-danger shadow" aria-labelledby="dropdownId">
                            <a class="dropdown-item drophovercustom" href="productos.html">Productos</a>
                            <a class="dropdown-item drophovercustom" href="pedidos.html">Pedidos</a>
                            <a class="dropdown-item drophovercustom" href="clientes.html">Clientes</a>
                        </div>
                    </li>
                </ul>
                <!-- <ul class="navbar-nav me-auto mt-2 mt-lg-0 " >
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuario</a>
                    </li>
                </ul> -->
                <span id="sesionlink"><a class="nav-link text-light sesiontext" href="login.html">Usuario</a></span>

            </div>
        </div>
    </nav>
    <div class="container">
        
      <div class="jumbotron-fluid pt-5 pb-3">
        <h3>Agrega al carrito tus productos</h3>
      </div>

        <!--  -->
        <div class="row mt-2">
            <div class="col-sm-4 p-3">
                <div class="card p-2 shadow">
                    <img class="card-img-top" src="img/electrica.jfif" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">Anguila Electrica Roll</h4>
                        <p class="card-text">Un sabor electrizante</p>
                        <a href="#" class="btn btn-primary">Agregar al pedido</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-3">
                <div class="card p-2 shadow">
                    <img class="card-img-top" src="img/pulporoll.jfif" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">Pulpo venenoso Roll</h4>
                        <p class="card-text">Abrazadoramente delicioso</p>
                        <a href="#" class="btn btn-primary">Agregar al pedido</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 p-3">
                <div class="card p-2 shadow">
                    <img class="card-img-top" src="img//sushipleto.jfif" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">Sushipleto</h4>
                        <p class="card-text">Típica picanteria Shilena</p>
                        <a href="#" class="btn btn-primary">Agregar al pedido</a>
                    </div>
                </div>
            </div>
        </div>



    </div>



</body>

</html>

sushi/templates/sushi/modificarproducto.html
{% extends "sushi/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="container">

    <div class="row mt-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="border shadow rounded p-5">
                <h3>Modificar Producto</h3>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-end">
                        <input type="submit" class="btn btn-warning btn-lg mt-2" value="Modificar">
                        <span> &nbsp;&nbsp;</span>
                        <a href="{% url "productos" %}">
                        <input type="button" class="btn btn-danger btn-lg mt-2"  value="Cancelar">
                        </a>
                        
                        
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>


</div>



{% endblock contenido %}

sushi/templates/sushi/productos.html
{% extends "sushi/base.html" %}
{% load static %}



{% block links %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock links %}




{% block contenido %}

    <div class="container"><!--main container-->
      <div class="mt-3">
        <h1 class="h4">Listado de Productos</h1>
        <p ><a href="{% url "crearproducto" %}" class="nodecolink"><i class="fa fa-plus-circle" aria-hidden="true"></i> Agregar un producto</p></a>
      </div>
      <div class="mt-2 table-responsive">
        <table class="table table-hover">
            <thead>
              <tr>
                <th>Id</th>
                <th>Producto</th>
                <th>Imagen</th>
                <th>Descripción</th>
                <th>Valor</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for p in productos  %}
              <tr>
                <td>{{p.id}}</td>
                <td>{{p.nombre_producto | title}}</td>
                <td><img src="{{p.imagen.url}} " alt="" height="50"></td>
                <td>{{p.descripcion | capfirst}}</td>

                <td>${{p.valor }}</td>
     
                <td>
                    <a href="{% url "modificarproducto" p.id %}" role="button" class="btn btn-warning text-light"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a href="{% url "eliminarproducto" p.id %}" role="button" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
                
              </tr>
              {% endfor %}
            </tbody>
        </table>
          <!--
          <ul class="pagination text-center">
            <li class="page-item"><a class="page-link" href="#">Anterior</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Siguiente</a></li>
            
          </ul>
          -->
          <div>
            {% include 'sushi/paginator.html' %}
          </div>
          

      </div>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_valor"></label>
          <input type="text" class="form-control" name="valor" id="id_valor" aria-describedby="helpId" placeholder="">
        </div>
        <input type="submit" value="buscar">
      </form>


    </div><!--main container ends-->

    {% endblock contenido %}